// flow-typed signature: 2021bf55e7425d237f4d100f355ed947
// flow-typed version: <<STUB>>/gulplog_v^1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulplog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulplog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulplog/index' {
  declare module.exports: $Exports<'gulplog'>;
}
declare module 'gulplog/index.js' {
  declare module.exports: $Exports<'gulplog'>;
}
