// flow-typed signature: 799dd0b7b1beb3e4bf349e59d3c40d04
// flow-typed version: <<STUB>>/gulp-babel_v^6.1.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'gulp-babel/index' {
  declare module.exports: $Exports<'gulp-babel'>;
}
declare module 'gulp-babel/index.js' {
  declare module.exports: $Exports<'gulp-babel'>;
}
