// flow-typed signature: e39b3257618f9eb363f166ae8ef6ceb4
// flow-typed version: <<STUB>>/gulp-changed_v^1.3.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-changed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-changed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'gulp-changed/index' {
  declare module.exports: $Exports<'gulp-changed'>;
}
declare module 'gulp-changed/index.js' {
  declare module.exports: $Exports<'gulp-changed'>;
}
