export const haste = [
  'ARTSerializablePath',
  'ActionSheetIOS',
  'ActivityIndicator',
  'Alert',
  'AlertIOS',
  'Animated',
  'AnimatedAddition',
  'AnimatedDiffClamp',
  'AnimatedDivision',
  'AnimatedEvent',
  'AnimatedImplementation',
  'AnimatedInterpolation',
  'AnimatedModulo',
  'AnimatedMultiplication',
  'AnimatedNode',
  'AnimatedProps',
  'AnimatedStyle',
  'AnimatedTracking',
  'AnimatedTransform',
  'AnimatedValue',
  'AnimatedValueXY',
  'AnimatedWeb',
  'AnimatedWithChildren',
  'Animation',
  'AppContainer',
  'AppRegistry',
  'AppState',
  'Array.es6',
  'Array.prototype.es6',
  'AssetRegistry',
  'AssetSourceResolver',
  'AsyncStorage',
  'BackAndroid',
  'BatchedBridge',
  'Batchinator',
  'Blob',
  'BlobTypes',
  'BorderBox',
  'BoundingDimensions',
  'BugReporting',
  'Button',
  'CameraRoll',
  'Clipboard',
  'ColorPropType',
  'DebugEnvironment',
  'DecayAnimation',
  'DeviceInfo',
  'Dimensions',
  'DocumentSelectionState',
  'Easing',
  'EdgeInsetsPropType',
  'ElementBox',
  'ElementProperties',
  'EmitterSubscription',
  'ErrorUtils',
  'EventEmitter',
  'EventEmitterWithHolding',
  'EventHolder',
  'EventSubscription',
  'EventSubscriptionVendor',
  'EventValidator',
  'ExceptionsManager',
  'FillRateHelper',
  'FlatList',
  'FormData',
  'FrameRateLogger',
  'Geolocation',
  'HMRClient',
  'HeapCapture',
  'I18nManager',
  'ImageBackground',
  'ImageEditor',
  'ImagePickerIOS',
  'ImageResizeMode',
  'ImageSource',
  'ImageSourcePropType',
  'ImageStore',
  'ImageStylePropTypes',
  'Incremental',
  'IncrementalGroup',
  'IncrementalPresenter',
  'InitializeCore',
  'InspectorAgent',
  'InspectorOverlay',
  'InspectorPanel',
  'InteractionManager',
  'InteractionMixin',
  'JSEventLoopWatchdog',
  'JSTimers',
  'Keyboard',
  'KeyboardAvoidingView',
  'LayoutAnimation',
  'LayoutPropTypes',
  'LazyRenderer',
  'Linking',
  'ListView',
  'ListViewDataSource',
  'Map',
  'MatrixMath',
  'MessageQueue',
  'MetroListView',
  'MissingNativeEventEmitterShim',
  'Modal',
  'NativeAnimatedHelper',
  'NativeEventEmitter',
  'NativeMethodsMixin',
  'NativeModules',
  'NetInfo',
  'NetworkAgent',
  'NetworkOverlay',
  'Number.es6',
  'Object.es6',
  'Object.es7',
  'PanResponder',
  'PerformanceLogger',
  'PerformanceOverlay',
  'PermissionsAndroid',
  'Picker',
  'PixelRatio',
  'PointPropType',
  'PooledClass',
  'Position',
  'Promise',
  'QuickPerformanceLogger',
  'RCTDeviceEventEmitter',
  'RCTEventEmitter',
  'RCTLog',
  'RCTNativeAppEventEmitter',
  'React',
  'ReactDebugTool',
  'ReactGlobalSharedState',
  'ReactNative',
  'ReactNativeART',
  'ReactNativeBridgeEventPlugin',
  'ReactNativeComponentTree',
  'ReactNativeFeatureFlags',
  'ReactNativePropRegistry',
  'ReactNativeStyleAttributes',
  'ReactNativeTypes',
  'ReactNativeVersion',
  'ReactNativeVersionCheck',
  'ReactNativeViewAttributes',
  'ReactPerf',
  'ReactTypes',
  'RefreshControl',
  'RelativeImageStub',
  'SamplingProfiler',
  'SceneTracker',
  'ScrollResponder',
  'ScrollView',
  'ScrollViewStickyHeader',
  'SectionList',
  'Set',
  'ShadowPropTypesIOS',
  'Share',
  'Slider',
  'SpringAnimation',
  'SpringConfig',
  'StaticContainer.react',
  'StaticRenderer',
  'StatusBar',
  'String.prototype.es6',
  'StyleSheet',
  'StyleSheetPropType',
  'StyleSheetTypes',
  'StyleSheetValidation',
  'Subscribable',
  'SwipeableFlatList',
  'SwipeableListView',
  'SwipeableListViewDataSource',
  'SwipeableQuickActionButton',
  'SwipeableQuickActions',
  'SwipeableRow',
  'Switch',
  'Systrace',
  'TVViewPropTypes',
  'TaskQueue',
  'Text',
  'TextInput',
  'TextInputState',
  'TextStylePropTypes',
  'TextUpdateTest',
  'TimingAnimation',
  'TouchHistoryMath',
  'Touchable',
  'TouchableBounce',
  'TouchableHighlight',
  'TouchableOpacity',
  'TouchableWithoutFeedback',
  'TransformPropTypes',
  'UIManager',
  'UIManagerStatTracker',
  'URL',
  'UnimplementedView',
  'Vibration',
  'View',
  'ViewAccessibility',
  'ViewPropTypes',
  'ViewStylePropTypes',
  'ViewabilityHelper',
  'VirtualizeUtils',
  'VirtualizedList',
  'VirtualizedSectionList',
  'WebSocket',
  'WebSocketEvent',
  'WebSocketInterceptor',
  'WindowedListView',
  'XHRInterceptor',
  'XMLHttpRequest',
  'YellowBox',
  '_shouldPolyfillES6Collection',
  'babelHelpers',
  'bezier',
  'binaryToBase64',
  'buildStyleInterpolator',
  'clamp',
  'console',
  'convertRequestBody',
  'createAnimatedComponent',
  'createReactNativeComponentClass',
  'createStrictShapeTypeChecker',
  'deepDiffer',
  'deepFreezeAndThrowOnMutationInDev',
  'defineLazyObjectProperty',
  'deprecatedPropType',
  'dismissKeyboard',
  'dumpReactTree',
  'ensureComponentIsNative',
  'ensurePositiveDelayProps',
  'error-guard',
  'fetch',
  'flattenStyle',
  'getDevServer',
  'getObjectValues',
  'getReactData',
  'groupByEveryN',
  'guid',
  'infoLog',
  'insetsDiffer',
  'isEmpty',
  'logError',
  'mapWithSeparator',
  'matricesDiffer',
  'merge',
  'mergeFast',
  'mergeHelpers',
  'mergeInto',
  'mergeIntoFast',
  'mixInEventEmitter',
  'nativeImageSource',
  'normalizeColor',
  'openFileInEditor',
  'parseErrorStack',
  'pointsDiffer',
  'processColor',
  'processDecelerationRate',
  'processTransform',
  'promiseRejectionIsError',
  'queryLayoutByID',
  'react-native-implementation',
  'react-native-interface',
  'renderApplication',
  'requireNativeComponent',
  'resolveAssetSource',
  'resolveBoxStyle',
  'setNormalizedColorAlpha',
  'setupDevtools',
  'sizesDiffer',
  'stringifySafe',
  'symbolicateStackTrace',
  'takeSnapshot',
  'toIterator',
  'truncate',
  'utf8',
  'verifyPropTypes',
  'AccessibilityInfo',
  'BackHandler',
  'CheckBox',
  'DatePickerAndroid',
  'DatePickerIOS',
  'DrawerLayoutAndroid',
  'HMRLoadingView',
  'Image',
  'MaskedViewIOS',
  'NavigatorIOS',
  'PickerAndroid',
  'PickerIOS',
  'Platform',
  'PlatformViewPropTypes',
  'ProgressBarAndroid',
  'ProgressViewIOS',
  'RCTAlertManager',
  'RCTNetworking',
  'SafeAreaView',
  'Sample',
  'SegmentedControlIOS',
  'Settings',
  'SnapshotViewIOS',
  'StatusBarIOS',
  'TVEventHandler',
  'TabBarIOS',
  'TabBarItemIOS',
  'TimePickerAndroid',
  'ToastAndroid',
  'ToolbarAndroid',
  'TouchableNativeFeedback',
  'VibrationIOS',
  'ViewPagerAndroid',
  'WebView',
  'react-native/Libraries/ART/ReactNativeART',
  'react-native/Libraries/Renderer/shims/ReactNativePropRegistry',
  'react-native/package',
];

export const dependencies = {
  '33.0.0': {
    '@expo/vector-icons': '8.1.0',
    expo: '33.0.0',
    'expo-font': '2.0.0',
    'lottie-react-native': '2.5.0',
    'react-native-maps': '0.22.1',
    'react-native-screens': '1.0.0-alpha.19',
    'react-native-gesture-handler': '1.0.12',
    'react-native-reanimated': '1.0.0-alpha.19',
    'react-native-svg': '8.0.10',
    'react-native-vector-icons': 'expo/vector-icons#8.1.0',
    'react-native': '0.59.8',
    react: '16.8.3',
    'expo-constants': '5.0.0',
    '@unimodules/core': '2.0.0',
    'expo-ads-admob': '5.0.0',
    'expo-ads-facebook': '5.0.0',
    'expo-app-auth': '5.0.0',
    'expo-asset': '5.0.0',
    'expo-av': '5.0.0',
    'expo-background-fetch': '5.0.0',
    'expo-barcode-scanner': '5.0.0',
    'expo-blur': '5.0.0',
    'expo-calendar': '5.0.0',
    'expo-camera': '5.0.0',
    'expo-constants': '5.0.0',
    'expo-contacts': '5.0.0',
    'expo-document-picker': '5.0.0',
    'expo-face-detector': '5.0.0',
    'expo-facebook': '5.0.0',
    'expo-file-system': '5.0.0',
    'expo-font': '5.0.0',
    'expo-gl': '5.0.0',
    'expo-google-sign-in': '5.0.0',
    'expo-haptics': '5.0.0',
    'expo-image-manipulator': '5.0.0',
    'expo-image-picker': '5.0.0',
    'expo-intent-launcher': '5.0.0',
    'expo-keep-awake': '5.0.0',
    'expo-linear-gradient': '5.0.0',
    'expo-local-authentication': '5.0.0',
    'expo-localization': '5.0.0',
    'expo-location': '5.0.0',
    'expo-mail-composer': '5.0.0',
    'expo-media-library': '5.0.0',
    'expo-permissions': '5.0.0',
    'expo-print': '5.0.0',
    'expo-processing': '~2.0.0',
    'expo-secure-store': '5.0.0',
    'expo-sharing': '^3.0.0',
    'expo-sms': '5.0.0',
    'expo-speech': '5.0.0',
    'expo-task-manager': '5.0.0',
    'expo-web-browser': '5.0.0',
  },
  '34.0.0': {
    '@expo/snack-static': '0.0.1',
    '@expo/snack-static/react-native-logo.png': '0.0.1',
    '@expo/vector-icons': '8.1.0',
    expo: '34.0.1',
    'expo-font': '2.0.0',
    'lottie-react-native': '2.5.0',
    'react-native-maps': '0.22.1',
    'react-native-screens': '1.0.0-alpha.19',
    'react-native-gesture-handler': '1.3.0',
    'react-native-reanimated': '1.1.0',
    'react-native-svg': '9.5.1',
    'react-native-vector-icons': 'expo/vector-icons',
    'react-native': '0.59.8',
    react: '16.8.3',
    'expo-constants': '5.0.0',
    '@unimodules/core': '2.0.0',
    'expo-ads-admob': '5.0.0',
    'expo-ads-facebook': '5.0.0',
    'expo-app-auth': '5.0.0',
    'expo-asset': '5.0.0',
    'expo-av': '5.0.0',
    'expo-background-fetch': '5.0.0',
    'expo-barcode-scanner': '5.0.0',
    'expo-blur': '5.0.0',
    'expo-calendar': '5.0.0',
    'expo-camera': '5.0.0',
    'expo-constants': '5.0.0',
    'expo-contacts': '5.0.0',
    'expo-document-picker': '5.0.0',
    'expo-face-detector': '5.0.0',
    'expo-facebook': '5.0.0',
    'expo-file-system': '5.0.0',
    'expo-font': '5.0.0',
    'expo-gl': '5.0.0',
    'expo-google-sign-in': '5.0.0',
    'expo-haptics': '5.0.0',
    'expo-image-manipulator': '5.0.0',
    'expo-image-picker': '5.0.0',
    'expo-intent-launcher': '5.0.0',
    'expo-keep-awake': '5.0.0',
    'expo-linear-gradient': '5.0.0',
    'expo-local-authentication': '5.0.0',
    'expo-localization': '5.0.0',
    'expo-location': '5.0.0',
    'expo-mail-composer': '5.0.0',
    'expo-media-library': '5.0.0',
    'expo-permissions': '5.0.0',
    'expo-print': '5.0.0',
    'expo-processing': '~2.0.0',
    'expo-secure-store': '5.0.0',
    'expo-sharing': '^3.0.0',
    'expo-sms': '5.0.0',
    'expo-speech': '5.0.0',
    'expo-task-manager': '5.0.0',
    'expo-web-browser': '5.0.0',
  },
  '35.0.0': {
    '@expo/snack-static': '0.0.1',
    '@expo/snack-static/react-native-logo.png': '0.0.1',
    '@expo/vector-icons': '10.0.0',
    expo: '35.0.0',
    'expo-font': '7.0.0',
    'lottie-react-native': '2.6.1',
    'react-native-maps': '0.25.0',
    'react-native-screens': '1.0.0-alpha.23',
    'react-native-gesture-handler': '1.3.0',
    'react-native-reanimated': '1.2.0',
    'react-native-svg': '9.9.2',
    'react-native-vector-icons': 'expo/vector-icons',
    'react-native': '0.59.8',
    react: '16.8.3',
    'expo-constants': '7.0.0',
    '@unimodules/core': '4.0.0',
    'expo-ads-admob': '7.0.0',
    'expo-ads-facebook': '7.0.0',
    'expo-app-auth': '7.0.0',
    'expo-asset': '7.0.0',
    'expo-av': '7.0.0',
    'expo-background-fetch': '7.0.0',
    'expo-barcode-scanner': '7.0.0',
    'expo-blur': '7.0.0',
    'expo-calendar': '7.0.0',
    'expo-camera': '7.0.0',
    'expo-constants': '7.0.0',
    'expo-contacts': '7.0.0',
    'expo-document-picker': '7.0.0',
    'expo-face-detector': '7.0.0',
    'expo-facebook': '7.0.0',
    'expo-file-system': '7.0.0',
    'expo-font': '7.0.0',
    'expo-gl': '7.0.0',
    'expo-google-sign-in': '7.0.0',
    'expo-haptics': '7.0.0',
    'expo-image-manipulator': '7.0.0',
    'expo-image-picker': '7.0.0',
    'expo-intent-launcher': '7.0.0',
    'expo-keep-awake': '7.0.0',
    'expo-linear-gradient': '7.0.0',
    'expo-local-authentication': '7.0.0',
    'expo-localization': '7.0.0',
    'expo-location': '7.0.0',
    'expo-mail-composer': '7.0.0',
    'expo-media-library': '7.0.0',
    'expo-permissions': '7.0.0',
    'expo-print': '7.0.0',
    'expo-secure-store': '7.0.0',
    'expo-sharing': '7.0.0',
    'expo-sms': '7.0.0',
    'expo-speech': '7.0.0',
    'expo-task-manager': '7.0.0',
    'expo-web-browser': '7.0.0',
  },
};
