export const haste = [
  'ARTSerializablePath',
  'ActionSheetIOS',
  'ActivityIndicator',
  'Alert',
  'AlertIOS',
  'Animated',
  'AnimatedAddition',
  'AnimatedDiffClamp',
  'AnimatedDivision',
  'AnimatedEvent',
  'AnimatedImplementation',
  'AnimatedInterpolation',
  'AnimatedModulo',
  'AnimatedMultiplication',
  'AnimatedNode',
  'AnimatedProps',
  'AnimatedStyle',
  'AnimatedTracking',
  'AnimatedTransform',
  'AnimatedValue',
  'AnimatedValueXY',
  'AnimatedWeb',
  'AnimatedWithChildren',
  'Animation',
  'AppContainer',
  'AppRegistry',
  'AppState',
  'Array.es6',
  'Array.prototype.es6',
  'AssetRegistry',
  'AssetSourceResolver',
  'AsyncStorage',
  'BackAndroid',
  'BatchedBridge',
  'Batchinator',
  'Blob',
  'BlobTypes',
  'BorderBox',
  'BoundingDimensions',
  'BugReporting',
  'Button',
  'CameraRoll',
  'Clipboard',
  'ColorPropType',
  'DebugEnvironment',
  'DecayAnimation',
  'DeviceInfo',
  'Dimensions',
  'DocumentSelectionState',
  'Easing',
  'EdgeInsetsPropType',
  'ElementBox',
  'ElementProperties',
  'EmitterSubscription',
  'ErrorUtils',
  'EventEmitter',
  'EventEmitterWithHolding',
  'EventHolder',
  'EventSubscription',
  'EventSubscriptionVendor',
  'EventValidator',
  'ExceptionsManager',
  'FillRateHelper',
  'FlatList',
  'FormData',
  'FrameRateLogger',
  'Geolocation',
  'HMRClient',
  'HeapCapture',
  'I18nManager',
  'ImageBackground',
  'ImageEditor',
  'ImagePickerIOS',
  'ImageResizeMode',
  'ImageSource',
  'ImageSourcePropType',
  'ImageStore',
  'ImageStylePropTypes',
  'Incremental',
  'IncrementalGroup',
  'IncrementalPresenter',
  'InitializeCore',
  'InspectorAgent',
  'InspectorOverlay',
  'InspectorPanel',
  'InteractionManager',
  'InteractionMixin',
  'JSEventLoopWatchdog',
  'JSTimers',
  'Keyboard',
  'KeyboardAvoidingView',
  'LayoutAnimation',
  'LayoutPropTypes',
  'LazyRenderer',
  'Linking',
  'ListView',
  'ListViewDataSource',
  'Map',
  'MatrixMath',
  'MessageQueue',
  'MetroListView',
  'MissingNativeEventEmitterShim',
  'Modal',
  'NativeAnimatedHelper',
  'NativeEventEmitter',
  'NativeMethodsMixin',
  'NativeModules',
  'NetInfo',
  'NetworkAgent',
  'NetworkOverlay',
  'Number.es6',
  'Object.es6',
  'Object.es7',
  'PanResponder',
  'PerformanceLogger',
  'PerformanceOverlay',
  'PermissionsAndroid',
  'Picker',
  'PixelRatio',
  'PointPropType',
  'PooledClass',
  'Position',
  'Promise',
  'QuickPerformanceLogger',
  'RCTDeviceEventEmitter',
  'RCTEventEmitter',
  'RCTLog',
  'RCTNativeAppEventEmitter',
  'React',
  'ReactDebugTool',
  'ReactGlobalSharedState',
  'ReactNative',
  'ReactNativeART',
  'ReactNativeBridgeEventPlugin',
  'ReactNativeComponentTree',
  'ReactNativeFeatureFlags',
  'ReactNativePropRegistry',
  'ReactNativeStyleAttributes',
  'ReactNativeTypes',
  'ReactNativeVersion',
  'ReactNativeVersionCheck',
  'ReactNativeViewAttributes',
  'ReactPerf',
  'ReactTypes',
  'RefreshControl',
  'RelativeImageStub',
  'SamplingProfiler',
  'SceneTracker',
  'ScrollResponder',
  'ScrollView',
  'ScrollViewStickyHeader',
  'SectionList',
  'Set',
  'ShadowPropTypesIOS',
  'Share',
  'Slider',
  'SpringAnimation',
  'SpringConfig',
  'StaticContainer.react',
  'StaticRenderer',
  'StatusBar',
  'String.prototype.es6',
  'StyleSheet',
  'StyleSheetPropType',
  'StyleSheetTypes',
  'StyleSheetValidation',
  'Subscribable',
  'SwipeableFlatList',
  'SwipeableListView',
  'SwipeableListViewDataSource',
  'SwipeableQuickActionButton',
  'SwipeableQuickActions',
  'SwipeableRow',
  'Switch',
  'Systrace',
  'TVViewPropTypes',
  'TaskQueue',
  'Text',
  'TextInput',
  'TextInputState',
  'TextStylePropTypes',
  'TextUpdateTest',
  'TimingAnimation',
  'TouchHistoryMath',
  'Touchable',
  'TouchableBounce',
  'TouchableHighlight',
  'TouchableOpacity',
  'TouchableWithoutFeedback',
  'TransformPropTypes',
  'UIManager',
  'UIManagerStatTracker',
  'URL',
  'UnimplementedView',
  'Vibration',
  'View',
  'ViewAccessibility',
  'ViewPropTypes',
  'ViewStylePropTypes',
  'ViewabilityHelper',
  'VirtualizeUtils',
  'VirtualizedList',
  'VirtualizedSectionList',
  'WebSocket',
  'WebSocketEvent',
  'WebSocketInterceptor',
  'WindowedListView',
  'XHRInterceptor',
  'XMLHttpRequest',
  'YellowBox',
  '_shouldPolyfillES6Collection',
  'babelHelpers',
  'bezier',
  'binaryToBase64',
  'buildStyleInterpolator',
  'clamp',
  'console',
  'convertRequestBody',
  'createAnimatedComponent',
  'createReactNativeComponentClass',
  'createStrictShapeTypeChecker',
  'deepDiffer',
  'deepFreezeAndThrowOnMutationInDev',
  'defineLazyObjectProperty',
  'deprecatedPropType',
  'dismissKeyboard',
  'dumpReactTree',
  'ensureComponentIsNative',
  'ensurePositiveDelayProps',
  'error-guard',
  'fetch',
  'flattenStyle',
  'getDevServer',
  'getObjectValues',
  'getReactData',
  'groupByEveryN',
  'guid',
  'infoLog',
  'insetsDiffer',
  'isEmpty',
  'logError',
  'mapWithSeparator',
  'matricesDiffer',
  'merge',
  'mergeFast',
  'mergeHelpers',
  'mergeInto',
  'mergeIntoFast',
  'mixInEventEmitter',
  'nativeImageSource',
  'normalizeColor',
  'openFileInEditor',
  'parseErrorStack',
  'pointsDiffer',
  'processColor',
  'processDecelerationRate',
  'processTransform',
  'promiseRejectionIsError',
  'queryLayoutByID',
  'react-native-implementation',
  'react-native-interface',
  'renderApplication',
  'requireNativeComponent',
  'resolveAssetSource',
  'resolveBoxStyle',
  'setNormalizedColorAlpha',
  'setupDevtools',
  'sizesDiffer',
  'stringifySafe',
  'symbolicateStackTrace',
  'takeSnapshot',
  'toIterator',
  'truncate',
  'utf8',
  'verifyPropTypes',
  'AccessibilityInfo',
  'BackHandler',
  'CheckBox',
  'DatePickerAndroid',
  'DatePickerIOS',
  'DrawerLayoutAndroid',
  'HMRLoadingView',
  'Image',
  'MaskedViewIOS',
  'NavigatorIOS',
  'PickerAndroid',
  'PickerIOS',
  'Platform',
  'PlatformViewPropTypes',
  'ProgressBarAndroid',
  'ProgressViewIOS',
  'RCTAlertManager',
  'RCTNetworking',
  'SafeAreaView',
  'Sample',
  'SegmentedControlIOS',
  'Settings',
  'SnapshotViewIOS',
  'StatusBarIOS',
  'TVEventHandler',
  'TabBarIOS',
  'TabBarItemIOS',
  'TimePickerAndroid',
  'ToastAndroid',
  'ToolbarAndroid',
  'TouchableNativeFeedback',
  'VibrationIOS',
  'ViewPagerAndroid',
  'WebView',
  'react-native/Libraries/ART/ReactNativeART',
  'react-native/Libraries/Renderer/shims/ReactNativePropRegistry',
  'react-native/package',
];

export const dependencies = {
  '24.0.0': {
    'expo': '24.0.0',
    'react-native-svg': 'expo/react-native-svg#5.5.1-exp.1',
    'react-native-vector-icons': 'expo/vector-icons#6.2.0',
    'react-native': '0.51.0',
    'react': '16.0.0',
    'three': '0.87.1',
  },
  '25.0.0': {
    'expo': '25.0.0',
    'react-native-svg': 'expo/react-native-svg#5.5.1-exp.1',
    'react-native-vector-icons': 'expo/vector-icons#6.2.0',
    'react-native': '0.52.0',
    'react': '16.2.0',
    'three': '0.89.0',
  },
  '26.0.0': {
    'expo': '26.0.0',
    'react-native-svg': '6.2.2',
    'react-native-vector-icons': 'expo/vector-icons#6.3.1',
    'react-native': '0.54.2',
    'react': '16.3.0-alpha.1',
    'three': '0.90.0',
  },
  '27.0.0': {
    '@expo/vector-icons': '6.3.1',
    'expo': '27.0.0',
    'react-native-gesture-handler': '1.0.0-alpha.41',
    'react-native-svg': '6.2.2',
    'react-native-vector-icons': 'expo/vector-icons#6.3.1',
    'react-native': '0.55.2',
    'react': '16.3.1',
    'three': '0.90.0',
  },
  '28.0.0': {
    '@expo/vector-icons': '6.3.1',
    'expo': '28.0.0',
    'react-native-gesture-handler': '1.0.4',
    'react-native-reanimated': '1.0.0-alpha.2',
    'react-native-svg': '6.2.2',
    'react-native-vector-icons': 'expo/vector-icons#6.3.1',
    'react-native': '0.55.4',
    'react': '16.3.1',
    'three': '0.90.0',
  },
  '29.0.0': {
    '@expo/vector-icons': '6.3.1',
    'expo': '29.0.0',
    'react-native-gesture-handler': '1.0.6',
    'react-native-reanimated': '1.0.0-alpha.3',
    'react-native-svg': '6.2.2',
    'react-native-vector-icons': 'expo/vector-icons#6.3.1',
    'react-native': '0.55.4',
    'react': '16.3.1',
    'three': '0.90.0',
  },
};
